all install:
	chmod +x essentials_setup.bash ros_setup.bash opencv_setup.bash kinect_setup.bash libfreenect2_setup.bash
	sudo ./essentials_setup.bash
	sudo ./ros_setup.bash
	sudo ./opencv_setup.bash
	sudo ./libfreenect2_setup.bash
	sudo ./kinect_setup.bash

essentials:
	chmod +x essentials_setup.bash ros_setup.bash opencv_setup.bash kinect_setup.bash libfreenect2_setup.bash
	sudo ./essentials_setup.bash

kinect:
	chmod +x essentials_setup.bash ros_setup.bash opencv_setup.bash libfreenect2_setup.bash kinect_setup.bash
	./kinect_setup.bash

libfreenect:
	chmod +x essentials_setup.bash ros_setup.bash opencv_setup.bash libfreenect2_setup.bash kinect_setup.bash
	sudo ./essentials_setup.bash
	sudo ./libfreenect2_setup.bash

libfreenect2:
	chmod +x essentials_setup.bash ros_setup.bash opencv_setup.bash libfreenect2_setup.bash kinect_setup.bash
	sudo ./essentials_setup.bash
	sudo ./libfreenect2_setup.bash

opencv:
	chmod +x essentials_setup.bash ros_setup.bash opencv_setup.bash libfreenect2_setup.bash kinect_setup.bash
	sudo ./essentials_setup.bash
	sudo ./opencv_setup.bash

ros:
	chmod +x essentials_setup.bash ros_setup.bash opencv_setup.bash libfreenect2_setup.bash kinect_setup.bash
	sudo ./essentials_setup.bash
	sudo ./ros_setup.bash

clean:
	chmod -x essentials_setup.bash ros_setup.bash opencv_setup.bash libfreenect2_setup.bash kinect_setup.bash

play:	
	sudo ~/libfreenect2/build/bin/Protonect
